vantage6/vantage6

vantage6-server/vantage6/server/resource/collaboration.py
Also added extra permission check (which before would have led to empty data)
Fix #204
=> Bugfix for GET /collaboration?organization_id=x if user does not have permission to view collaborations globally

vantage6-server/vantage6/server/_data/example_fixtures.yaml, vantage6-server/vantage6/server/_data/unittest_fixtures.yaml, vantage6-server/vantage6/server/controller/fixture.py, vantage6/vantage6/cli/server.py
This prevents they are unknown after the import. Also added `--mount-src` option to `vserver import` while I was at it.
Fix #55 
Note: when releasing this, we should also update the documentation [here](https://docs.vantage6.ai/usage/running-the-server/importing-entities) with the new content of example_fixture.yaml (see code changes)
=> Require that API keys are defined in vserver import files. 

vantage6-server/vantage6/server/resource/task.py
For #208. Note that there could be a conflict with #203 where default roles are created. These should not include the 'edit task' rules if both PRs are merged
=> Remove unused rules to edit tasks

vantage6-server/tests_server/test_resources.py, vantage6-server/vantage6/server/permission.py, vantage6-server/vantage6/server/resource/user.py
Fix #51 
Introduced a check for both roles and rules that if user A wants to delete them for user B, user A should have the role/rule themselves.
=> Check permission when deleting roles/rules from user

vantage6-server/vantage6/server/resource/node.py
They are dissmilar now:
Fix #211
=> Using UUID4 instead of UUID1 to generate API keys for nodes

vantage6-client/vantage6/client/__init__.py
The default is now in line with all other list functions
Fix #238
=> Change default for pagination metadata inclusion in listing organizations in the Python client

vantage6-server/vantage6/server/resource/role.py
Users with organization-level permission to view roles were able to see their organization's roles, but not the new default roles that are available to all organizations. That is corrected here.
=> Always yield default roles in GET `/role`

vantage6-server/vantage6/server/resource/collaboration.py
Some `Unauthorized` actions on GET `/collaboration` did not get a status 401 returned explicitly. Therefore, a status 200 was returned as default status. This has been fixed herein.
=> Added missing error statuses for GET /collaboration endpoint

vantage6-client/requirements.txt, vantage6-client/setup.py
Fix #266 
Motivation for using v1.3.5: 1.3 is still [compatible with python 3.7](https://pandas.pydata.org/pandas-docs/version/1.3/getting_started/install.html) whereas 1.4 is [not](https://pandas.pydata.org/pandas-docs/version/1.4/getting_started/install.html)
=> Freeze pandas version: use latest pandas that is python v3.7 compatible

vantage6-server/vantage6/server/model/base.py
Creating new column in user table failed because user is reserved keyword in postgres, so now the tablename is surrounded by double quotes to mitigate that
Fix #411
=> Fix for creating columns in user table in postgres.

vantage6/vantage6/cli/node.py
… instead of default .csv
Fix #397
=> When loading a database file into the node, keep the original extension

vantage6-client/vantage6/client/__init__.py, vantage6-client/vantage6/tools/docker_wrapper.py, vantage6-node/vantage6/node/docker/task_manager.py, vantage6/vantage6/cli/node.py
Fix #398.
This wrapper passes the following as 'data' to an algorithm:
```{'my_label': '/mnt/data/my_label.csv', 'default': '/mnt/data/default.csv}```
The algorithm is then responsible itself to read these datafiles (e.g. `pd.read_csv(data['my_label'])`. I made that choice to allow passing databases of different types to the algorithm.
=> Implementation of multi db wrapper

vantage6-server/vantage6/server/__init__.py, vantage6-server/vantage6/server/default_roles.py, vantage6-server/vantage6/server/globals.py, vantage6-server/vantage6/server/permission.py, vantage6-server/vantage6/server/resource/role.py
Fix #442 (in a different/better way than was originally intended)
- When a new rule is created, it is assigned to the Root user automatically
As this is done based on matching by name Root, also the following was changed:
- Users cannot create roles with any of the default role names
- Users cannot change names of existing roles into any of the default role names
- The names of default roles cannot be changed
Finally, this lead to the introduction of an Enum to keep track of the default role names, and use that wherever it should be used.
=> Assign rules to root automatically, extra check on role name in POST/PATCH role

vantage6-server/tests_server/test_models.py, vantage6-server/tests_server/test_resources.py, vantage6-server/vantage6/server/db.py, vantage6-server/vantage6/server/model/base.py, vantage6-server/vantage6/server/session.py
Fix #53 
Resolved this by putting the `session` variable in `db.py` into its own separate file, `session.py`.
Then it was much easier than expected...
Tested that nodes can still connect, API still works, and vserver shell still works
=> Resolve circular import db session

vantage6-node/vantage6/node/socket.py, vantage6-server/vantage6/server/__init__.py, vantage6-server/vantage6/server/globals.py, vantage6-server/vantage6/server/model/node.py
Fix #40
Note that the node status will not be correct when starting up a server, and will only be correct when the full polling cycle has completed (takes about a minute). 
Two choices may be made: assume 1) all nodes are offline or 2) assume the same status as the last time the server was online.
For now I chose option 2.
=> Implemented ping/pong via socket to establish which nodes are online/offline more reliably

vantage6-node/vantage6/node/__init__.py, vantage6-node/vantage6/node/docker/vpn_manager.py, vantage6-server/vantage6/server/exceptions.py, vantage6-server/vantage6/server/resource/vpn.py
Fix #278 
In working on this, I also noticed a design error if someone defines a subnet in the node configuration file that doesn't match the subnet in which VPN IPs are provided. Then, there was no error of any kind, however the VPN connection would not have worked because the IP tables rules were generated for the wrong subnet. This has now been resolved with an extra check: when the VPN is connected, check if the VPN IP falls within the node subnet range; otherwise give an error and turn VPN off explicitly
=> Improved vpn error handling

tools/update-discord.py
There were links to the old documentation, these should be corrected.
I suggest merging them directly into main, so that the links are updated for any next release
=> Updated links in discord notification of new release

vantage6/vantage6/cli/node.py
If we get an exception, it is safe to assume the database is not a file
Fix #502
=> Catch exceptions on checking if a database if a file.

vantage6-node/vantage6/node/docker/vpn_manager.py
Latest versions of VPN images were not pulled automatically on node startup. This is now fixed
=> Pull latest versions of VPN images automatically

vantage6-server/vantage6/server/model/base.py, vantage6-server/vantage6/server/websockets.py
Socket events were opening database sessions but not closing them - e.g. to check user permissions in JWT decorators
New attempt:
Fix #534
=> Cleanup database sessions after socket events

vantage6-node/vantage6/node/docker/task_manager.py
=> Limit the number of characters of the input printed to the logs

vantage6-server/tests_server/test_resources.py, vantage6-server/vantage6/server/__init__.py
- No longer starting ping/pong in a separate thread but in a socketio background task to prevent complications
- Whether nodes responded to ping is now based on last_seen state and not on a list. The latter is not reliable with multiple server instances
=> Improved ping/pong between server and nodes

.readthedocs.yml
See that it is working here:
https://docs.vantage6.ai/en/bugfix-readthedocs-fails/technical-documentation/api/server.html
=> replaced legacy settings

docs/algorithms/classic_tutorial.rst, vantage6-client/vantage6/client/__init__.py, vantage6-node/vantage6/node/proxy_server.py, vantage6-node/vantage6/node/server_io.py, vantage6-server/vantage6/server/__init__.py
This should be everything to rename result to run
We only should have a discussion regarding the endpoint `/task/<id>/run`. This now gives all run details including the result. We may consider creating a separate `/task/<id>/result` just for the result
=> rename result to run - more changes

vantage6-client/vantage6/client/__init__.py, vantage6-client/vantage6/client/algorithm_client.py, vantage6-node/vantage6/node/proxy_server.py, vantage6-server/tests_server/test_resources.py, vantage6-server/vantage6/server/resource/common/_schema.py, vantage6-server/vantage6/server/resource/task.py
- Removed endpoint /task/<id>/run, which is superseded by modern alternative /run?task_id=<id>
- Adapted proxy server and algorithm client to that
- `/task?include=results` now only includes the result, not all other fields
I think with this, all changes required for #436 are done.
=> Last changes for renaming result to run

services/vpn-client/entry.sh
In the previous situation, the isolated subnet was not always immediately available when the eth1_interface was, so now it is included in the while loop
This explains the behaviour we saw where sometimes it worked and sometimes it didn't
Fix #671
=> Fix being able to connect to algorithms on same node on startup of VPN

vantage6-common/vantage6/common/context.py
Small error introduced earlier in release/3.9 branch
=> Fix missing class attribute instance_type in servercontext

.github/workflows/release.yml, docs/node/use.rst, vantage6-client/vantage6/client/__init__.py, vantage6-client/vantage6/client/_version.py, vantage6-common/vantage6/common/_version.py, vantage6-common/vantage6/common/globals.py, vantage6-node/vantage6/node/_version.py, vantage6-server/vantage6/server/_version.py, vantage6/tests_cli/test_node_cli.py, vantage6/vantage6/cli/_version.py, vantage6/vantage6/cli/node.py
Also, delete an extra dot in the version for pre-releases
Fix #700 
**Don't merge this yet, we may need to upgrade the policy (now using exact server version**
=> Startup the node with the same image version as the server is running on

docker-compose.yml, docs/devops/contribute.rst, docs/function-docs/server.rst, vantage6-server/vantage6/server/cli/server.py
Removed `vserver-local` commands `start`, `files`, `new` and `list` which were not used
Left the commands `import`, `version` and `shell`, which are still useful commands that are being run from the regular CLI in a Docker container.
Fix #663
=> Removed unused vserver-local commands

vantage6-server/tests_server/test_resources.py, vantage6-server/vantage6/server/permission.py
Previously, user A would have to have the exact same permissions as user B. Now, if user A has permission to create users with scope collaboration, they will also be able to assign that permission with lower scope (i.e. organization) to user B.
Fix #443
=> Updated check when user A tries to change permissions of user B.

vantage6/setup.py
Not doing so will cause them not to be loadable when running the commands from a non-development installation
=> Include the jinja2 templates for the vdev commands in the CLI packages.

vantage6/tests_cli/test_node_cli.py
This was annoying me already for ages, thought I should do something about it :-)
=> In CLI unittest, clean up the test private key file

vantage6/vantage6/cli/node.py
When a custom image was supplied in the node configuration file it was overruled by the server version.
=> custom image > server version

vantage6-client/vantage6/client/__init__.py
Without this I got the following when calling `client.task.create()` without a `databases` argument:
```
File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\420rc1\lib\site-packages\vantage6\cli\test\common\diagnostic_runner.py", line 122, in vpn_features
task = self.client.task.create(
File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\420rc1\lib\site-packages\vantage6\client\filter.py", line 93, in wrapper_filter
dict_ = func(*args, **kwargs)
File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\420rc1\lib\site-packages\vantage6\client\filter.py", line 178, in wrapper_filter
return func(*args, **kwargs)
File "C:\Users\bbe2101.54580\AppData\Local\miniconda3\envs\420rc1\lib\site-packages\vantage6\client\__init__.py", line 1241, in create
databases = …
```
=> Prevent error if no databases are defined

vantage6-common/vantage6/common/configuration_manager.py, vantage6/vantage6/cli/configuration_manager.py
Culprit was obligatory 'api_path' key that was not properly raised
=> Fix algorithm store config file that was empty

vantage6-algorithm-tools/vantage6/algorithm/tools/wrap.py
@anjavangestel ran into it that this information was not very helpful. Especially when importing the module, printing traceback can be nice to see what goes wrong in importing
=> Added extra logging if module or function fails to be imported

.github/workflows/release.yml
The new action doesn't use outdated nodejs commands
=> Update checkout action from v3 to v4

vantage6-common/vantage6/common/docker/addons.py, vantage6/vantage6/cli/node/stop.py
Prevent error on deleting docker volumes
- catch error if docker volume is still in use
- prevent that the error is generated at all by sleeping 1 second between removing the container and deleting its volumes
=> Prevent error on deleting docker volumes

vantage6-ui/src/app/models/constants/wait.ts, vantage6-ui/src/app/pages/task/create/steps/database-step/database-step.component.html, vantage6-ui/src/app/pages/task/create/steps/database-step/database-step.component.ts, vantage6-ui/src/app/pages/task/create/task-create.component.ts, vantage6-ui/src/assets/localizations/en.json
- if multiple nodes are online, pick one that shares configuration
- fix bug in creating error messages that node configuration could not be retrieved
- error messages if databases could not be retrieved from the node configuration in creating tasks
=> Improved how node configuration is retrieved and handled in the UI

.github/workflows/release.yml, Makefile
Since make will set command line variables to environment variables in subcommands, I use a slightly oddly named 'PUSH_REG' in case any command modifies behavior on 'PUSH' env var set.
This addresses https://github.com/vantage6/vantage6/issues/1191
=> Modify `make` to not push to registry by default after build

vantage6-ui/src/app/pages/collaboration/read/collaboration-read.component.html
The button should not be shown if there is nothing to be done
=> Don't show button to register nodes if all nodes are already registered

README.md
- Codacy link was wrong
- DOI badge linked to a 3.5.2 version - now it links to latest
Note that I only really updated those two lines - the other changes are from a markdown extension that reformats stuff.
=> Improve codacy and DOI badges

docs/server/deploy.rst
Fixes #1224 
I did not document the ARR affinity option for Azure as there was no section for this yet. I opened a separate issue for this: https://github.com/vantage6/vantage6/issues/1269
=> Added sticky sessions requirement to the docs for horizontal scaling

vantage6-ui/src/app/models/forms/login-form.model.ts, vantage6-ui/src/app/pages/auth/password-lost/password-lost.component.html, vantage6-ui/src/app/pages/auth/password-lost/password-lost.component.ts, vantage6-ui/src/app/services/auth.service.ts, vantage6-ui/src/assets/localizations/en.json
Fixes #1121 
Note that I left in the code that can handle both email and username. I felt like leaving it in in case we had a change or hearth. But let me know if it needs te be removed.
=> Removed username field from password recovery form

vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
When this was not done subsequent calls of partial functions could end up with a modified dataframe. Something that is not consistent with how this works in the infrastructure.
=> Copied all dataframes before supplying them to the partial functions in the `MockClient`

vantage6-node/vantage6/node/proxy_server.py
Partially undoing changes from #1268 - tasks where hanging whenever they tried `client.result.get()`. 
I did not really look into why `response.headers.items()` is causing this but after deleting it, everything worked fine. To be sure that we're not introducing new bugs I removed them everywhere where they were not yet present.
=> Prevent proxy requests from hanging by not returning headers

vantage6-algorithm-tools/setup.py
A wrong path to the tools directory (where the file is not present) was given
=> Include build file in the vantage6 algorithm client package

vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
This branched of main. The additional commits shown here should disappear when `main` is merged back into this release branch. Alternatively we could merge it into main.. its just docs
=> Added missing algorithm argument types in the documentation

vantage6-server/vantage6/server/__init__.py
This is a minor fix that seems to address issue #1333: random socket.io error (socketio.exceptions.BadNamespaceError: /tasks is not a connected namespace) on the v6 nodes while trying to share its parameters with the server during its initialization. It is based on this discussion thread ([Client is getting socketio.exceptions.BadNamespaceError after reconnecting · Issue #920 · miguelgrinberg/python-socketio (github.com)](https://github.com/miguelgrinberg/python-socketio/issues/920)). I tested this with a server running with the 'patched' code within a SURF-RC workspace, and a node running on a separate one (also on SURF). When I removed the 'always_connect' option and restarted the server and the node, the problem occurred again.
The [official …
=> Addressing random BadNameSpace error by including the 'always_connect' option to Socket.io

vantage6/vantage6/cli/context/node.py
=> Pass on print_log_header argument properly in v6 node stop

vantage6-server/vantage6/server/resource/vpn.py
Apparently the api for authenticating in eduvpn has changed, so I added another parameter.
I kept the old parameter for backward compatibility and eduvpn doesn't seem to mind.
=> Patch eduvpn3 4.7

vantage6-algorithm-store/requirements.txt, vantage6-algorithm-store/setup.py, vantage6-common/vantage6/common/docker/addons.py, vantage6/vantage6/cli/algostore/start.py
The algo store should not have to mount the docker socket just to get image digests - this requirement is dropped by this PR. 
Meanwhile the node continues to use the Docker SDK 
Let's see if we merge this into 4.6 and release 4.6.2 or if we include it in 4.7.0
=> Getting digests via manifests to prevent dependency store on docker socket

vantage6-server/vantage6/server/default_roles.py, vantage6-ui/src/app/pages/analyze/task/create/task-create.component.ts, vantage6-ui/src/app/pages/analyze/task/read/task-read.component.html, vantage6-ui/src/app/pages/analyze/task/read/task-read.component.ts, vantage6-ui/src/assets/localizations/en.json, vantage6-ui/src/environments/environment.development.ts
Server:
- add rule 'view events on collaboration scope' to all default roles. Without this, they cannot receive socket events such as algorithm updates and node statuses for other nodes in their collaboration, which is very inconvenient and leads e.g. to tasks hanging in 'pending' in the UI (fix #1478)
UI:
- extra check to prevent racing condition to prevent that task status updates get stuck on read task page (other part fix #1478)
- fix for repeating task with boolean values: set them by default to false
- Prevent that users can submit the task multiple times on create task page if it doesn't respond quick enough
- keep task status (folded) when task is finished, fix #1445
- also show log file on successfully completed algorithm runs, fix #1472
=> Small changes to running tasks in the UI - and change to default roles

vantage6-algorithm-store/tests_store/resources/test_v6server.py, vantage6-algorithm-store/vantage6/algorithm/store/resource/vantage6_server.py, vantage6-server/vantage6/server/algo_store_communication.py
Fixes #1460 
When adding a store to the server, the store tried to whitelist the server. In case the server was already whitelisted, an error was returned and the store could not be added. 
The case in which an already whitelisted server tries to be whitelisted again returns a different response. In this way, the server is not added twice to the db, but the process is not blocked.
=> Fix add already whitelisted server to store

docs/node/node_config.yaml, vantage6-node/vantage6/node/docker/docker_manager.py, vantage6-node/vantage6/node/docker/task_manager.py
Folders can be used for permanent storage between runs (e.g. caching). This is particularly useful when using duckdb. 
Adding functionality to support read-only mounts should be trivial.
=> Added functionality to mount folders (as databases)

vantage6-ui/src/app/components/table/table.component.html
Fixes #1572 => warning for unnecessary optional chain operation:
=> #1572 removed optional chain operation

vantage6-ui/src/app/services/api.service.ts
When going to algorithm store management pages, and user is not registered in a store, checking their permission gives a 403. This was not caught properly leading to an error message in the UI - while everything was functional as they are not allowed to change anything but maybe see algorithms. Now the error is caught
=> Handle error when user is not registered in algorithm store

vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py, vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
Containers do not have permission to get node details so the algorithm client function always yielded an error. Users should use the client.organization.get() as those IDs have to be provided for new tasks. Functions have now been removed to avoid confusion and more of these errors
=> Remove client.node.get() from algorithm client and mock algorithm client

vantage6-node/vantage6/node/k8s/container_manager.py
Just a simple fix to an error that was making the node crash.
=> fix: accessing the log before creating it on container_manager

charts/node/templates/node-deployment.yml, charts/server/templates/ui/ui-deployment.yml, dev/load-basic-fixtures.py, devspace.yaml, vantage6/vantage6/cli/template/node_config.j2
Hi @frankcorneliusmartin and @bartvanb 
Today I've been working on the last version of the integrated codebase and have fixed a couple of details that were making my dev environment fail. In particular, for your consideration:
- In some parts, the server API Path was set as /server, and in others as /api. I made changes to make these names consistent. This also required changing the node's jinja template, as it had the api_path hard coded as '/api'. @bartvanb I guess this may cause a conflict with the config-generation tools, so please let me know what you think.
- In some host configurations (like mine) the name `host.docker.internal` is not properly resolved. This name is now used across many points within the devspace environment so changing (e.g. to `172.17.0.1`) it is difficult and …
=> [k8s] Fixing dev environment issues

docs/server/yaml/server_config.yaml, vantage6-server/tests_server/test_cleanup.py, vantage6-server/vantage6/server/__init__.py, vantage6-server/vantage6/server/controller/cleanup.py, vantage6-server/vantage6/server/model/run.py, vantage6-server/vantage6/server/model/task.py, vantage6/vantage6/cli/configuration_manager.py
Server-enforced policy to delete results older than a certain number of days.
I opted for "clearing" results field instead of deleting tasks. For audibility purposes we might want to keep task logs and other metadata. I'm assuming here 'results' is where the potentially sensitive data might exist that a server admin might not want to keep indefinitely.
I considered celery, schedule, apscheduler, etc. but I don't think this feature is worth adding more dependencies and complexity — feature is disabled by default, and kept very simple for now.
A `lifetime` parameter (as mentioned https://github.com/vantage6/vantage6/issues/1560) can still fit with these changes in the future. However, this PR is coming from the perspective of the server administrator / collaboration policy, not a …
=> Add results_cleanup_days option to server

charts/server/values.yaml, charts/store/values.yaml, devspace.yaml
I observed that sometimes either the V6-Server database or the Store database is not initialized. According to the logs, this initialization is skipped due to an existing datafile. After that, there were errors of the type 'vantage6' / 'store' database doesn't exist.
I think this is because both PSQL services were using the same data file. I created separate ones for each one and haven't seen these errors back.
=> Fixing race condition when initializing server and store postgresSQL instances

devspace.yaml, vantage6-node/dev_start.sh, vantage6-node/vantage6/dev_start.py
Logs were duplicated as logs were written in several threads and probably due to logger singletons this led to multiple copies of each log statement
=> Fix duplicated node logging in v5 dev env

docs/server/deploy.rst
Reported by Narasimha Raghavan
=> Adapt path of socket.io to prevent socket 404 errors. 

vantage6-client/vantage6/client/subclients/dataframe.py
Redefining the client method that creates a new dataframe in a session, given the schema used by its corresponding API resource-handler (see issue #1883)
=> Fixing python client : session's dataframe creation

.gitignore
By default the `.tasks` directory is used in the repository folder (for linux/macos), lets ignore it :)
I dont know why the unittest are failing, but I geuss that is already the case in the release branch? Anyway this change did not break it.
=> Ignore default devspace tasks folder

vantage6-ui/src/app/pages/store/algorithm/list-public/algorithm-list-public.component.html, vantage6-ui/src/app/pages/store/algorithm/list/algorithm-list.component.html
Not showing status badges for now, because in community store everything would be "approved" and in the v6 UI there's separate pages for the different statuses.
=> No status badges for now

charts/server/templates/ui/ui-service.yml, charts/server/values.yaml, devspace.yaml
Solve #1782.
Note that:
1. Docker k8s supports load balancer, so the external IP would be `localhost` for dev env
2. Microk8s does does not natively have load balancer, so to use LoadBalancer service for dev env, you can use https://metallb.io/ to enable load balancer, or use `kubectl port-forward svc/vantage6-server-vantage6-frontend-service  7600:7600` to port forwarding the service. (these should be put to doc)
=> Change/1782 port forward UI k8s service

dev/populate_server.sh, dev/purge_data.sh, devspace.yaml
Fix #1929, https://github.com/vantage6/vantage6/issues/1785#issuecomment-2866695484
Not fix but prevent the #1942 (commit [f4f086f](https://github.com/vantage6/vantage6/pull/1930/commits/f4f086f9be4deab1adcf38c6665764c5baa0935e))
Related: merge #1891 first to make sure database and task data persist after running `devspace run stop-dev`.
=> Use only command `start-dev` to start dev env

vantage6-node/vantage6/node/k8s/container_manager.py
Not all job pods have secrets, therefore I accept 404 status codes to be returned when deleting run secrets.
Fixes the namespace error in #1941
=> Only non 404 errors are logged as error when removing run secrets

vantage6-node/vantage6/node/globals.py
Checked it with the extraction algorithm:
```
LOGS of POD run-1-gbj2v (created by job run-1) 
info > wrapper for v6-session-basics
info > Reading input file /app/vantage6/task/input
info > Dispatching ...
info > Module 'v6-session-basics' imported!
[[32minfo [0m] - Validating function action: data extraction
[[32minfo [0m] - Reading CSV file from /app/databases/default.csv
[[32minfo [0m] - Converting algorithm output to a Parquet Table.
info > Writing output to /app/vantage6/task/output
[0m 
```
=> Updated the algorithm internal IO paths

charts/auth/values.yaml, vantage6-algorithm-tools/vantage6/algorithm/decorator/metadata.py, vantage6-server/tests_server/test_resource_base.py, vantage6-server/vantage6/server/resource/__init__.py, vantage6-server/vantage6/server/resource/token.py
Not a full fix for supporting external keycloak, just a rename of the custom client_type claim in this PR
=> Rename client_type claim to vantage6_client_type

vantage6-common/vantage6/common/enum.py, vantage6-server/vantage6/server/resource/run.py, vantage6-ui/src/app/pipes/order-by-status.pipe.ts
Also, improved determining which tasks are dependent on a certain task by fully recursing down the tree, and also added missing runstatuses to the UI code
Triggered by this comment which was in the sessions overview issue: https://github.com/vantage6/vantage6/pull/1247#discussion_r1850409948
=> Setting specific status to runs that depend on tasks that failed

charts/store/templates/server/store-configmap.yml, vantage6-server/vantage6/server/__init__.py
* Tested it with a custom build in the IDEA4RC project
* I did not disable the IAT check as this was not easily configurable in the Flask-JWT-extended function interfaces and this seems like a proper fix.
=> Add JWT decode leeway configuration option in ServerApp

vantage6-server/vantage6/server/resource/blobstream.py
Uwsgi is not available when running outside of a uwsgi process, (see https://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html). When importing data in vs dev create-demo-network, aModuleNotFoundError is thrown if this resource is loaded. 
The proper fix will be to eventually find another way to stream without the use of uwsgi imports, until then a try catch is the best solution.
=> Add try catch to uwsgi import for when it is running outside of a wsgi process

vantage6-common/vantage6/common/globals.py
Currently the default chunk size for streaming is small, since we will not usually care about latency and current performance is slow, set a more sensible default.
=> Switch to more sensible chunk size default for improved performance
