vantage6-server/vantage6/server/resource/organization.py

Fix swagger formatting error. Fix #234

Show GET /organization without ID in swagger docs

---

vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/default_roles.py
vantage6-server/vantage6/server/model/rule.py

Added default roles 

---

vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/proxy_server.py

Rewrite is based on the rewrite in vantaget6 v2 (https://github.com/IKNL/vantage6-node/pull/83)
Fix #172

Rewritten proxy server

---

vantage6-client/vantage6/client/__init__.py
vantage6-common/vantage6/common/exceptions.py
vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/globals.py
vantage6-server/vantage6/server/resource/token.py
vantage6/vantage6/cli/globals.py

Instead of trying 10 times
Fix #169

Exit immediately if node tries to authenticate with wrong API key

---

vantage6-server/vantage6/server/resource/role.py

Added option to filter GET /role by user_id

---

vantage6-server/vantage6/server/resource/role.py

Fix #206. This was really an easy fix

Added check if role exists instead of returning empty json in GET role/<id>

---

vantage6-server/vantage6/server/resource/role.py

Fix bug where GET role with argument organization_id=x crashed

---

vantage6/tests_cli/test_node_cli.py
vantage6/vantage6/cli/node.py
vantage6/vantage6/cli/server.py

Added log message that node/server is still running when someone closes log stream

---

.github/workflows/unit_tests.yml
Makefile
requirements.txt
vantage6-client/requirements.txt
vantage6-client/setup.py
vantage6-client/vantage6/client/__init__.py
vantage6-client/vantage6/client/_version.py
vantage6-client/vantage6/tools/dispatch_rpc.py
vantage6-common/requirements.txt
vantage6-common/vantage6/common/_version.py
vantage6-node/requirements.txt
vantage6-node/setup.py
vantage6-node/vantage6/node/_version.py
vantage6-node/vantage6/node/server_io.py
vantage6-server/requirements.txt
vantage6-server/setup.py
vantage6-server/tests_server/test_resources.py
vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/_version.py
vantage6-server/vantage6/server/cli/server.py
vantage6-server/vantage6/server/resource/__init__.py
vantage6-server/vantage6/server/resource/token.py
vantage6/requirements.txt
vantage6/vantage6/cli/_version.py

Removed deprecated verify argument from jwt decode; updated PyJWT version

---

vantage6-server/vantage6/server/resource/organization.py

Also removed some logging that was appearing many times and didn't add anything
This is not linked to any issue (just something I came across)

Small simplification of GET organization endpoint permission checks 

---

vantage6-server/tests_server/test_resources.py
vantage6-server/vantage6/server/resource/user.py

Check if password criteria are met when creating a user

---

vantage6-client/vantage6/client/__init__.py
vantage6-server/vantage6/server/model/organization.py
vantage6-server/vantage6/server/resource/_schema.py

We should update this code before we go to version 4.0
It's a really horrible fix. There even has to be an import inside a function to prevent circular imports

Quick and dirty fix to make GET /organization quicker 

---

.github/workflows/release.yml
vantage6-server/tests_server/test_resources.py
vantage6-server/vantage6/server/resource/node.py

Fix #309. Node IP was not actually handled in the patch node endpoint, which is why it wasn't saved in the database..

Add node VPN IP address as possible field in node patch

---

vantage6-client/vantage6/client/__init__.py

Updated path to change password route in the client which was out of date

---

vantage6-client/vantage6/client/__init__.py

Add option to filter role list by user id

---

vantage6-client/vantage6/client/__init__.py

Removed the default filter that only offline nodes are shown when using client.node.list()

---

vantage6-client/vantage6/client/__init__.py
vantage6-client/vantage6/tools/dispatch_rpc.py
vantage6-node/vantage6/node/server_io.py

Remove backwards compatility to read JWT tokens for version v3.0-3.2 in v4

---

vantage6-client/setup.py
vantage6-client/vantage6/tools/docker_wrapper.py

I created a wrapper for parquet files.

337 feature request docker wrapper for parquet files

---

vantage6-server/vantage6/server/model/base.py

On server startup, add columns in the database if they were missing

---

tools/update-discord.py

The only relevant change is the one in line 32. Rest are PEP8 fixes.

Update channel for discord announcements. Also PEP8 fixes

---

vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/resource/__init__.py

and which user/node/container is doing it (only for authenticated requests)
Fix #295

Logging endpoint on each request

---

docs/algorithms/concepts.rst

Just a single codeblock.
Closes #401

Added parquet wrapper codeblock

---

vantage6-common/vantage6/common/docker/addons.py
vantage6-node/vantage6/node/docker/vpn_manager.py

Fix to pull docker images from docker hub if not found locally or remotely

---

vantage6-server/vantage6/server/resource/user.py

Added check so users cannot change usernames of other users

---

vantage6-server/vantage6/server/resource/user.py

Fix #334 
Also added checks to username and email that they are not allowed to be empty.

Propagate empty values in patch user to database

---

vantage6-node/vantage6/node/docker/docker_manager.py
vantage6-node/vantage6/node/socket.py

Fix additional comments on #167

Correct passing parameters of killed algorithms

---

vantage6-common/vantage6/common/docker/addons.py
vantage6-node/vantage6/node/docker/vpn_manager.py
vantage6-server/vantage6/server/resource/vpn.py

We don't need to pull the image, we only need to get the image object
Also, improved some comments
Fix #422

Fix bug when reading the ports from the algorithm image

---

vantage6-node/vantage6/node/docker/exceptions.py
vantage6-node/vantage6/node/proxy_server.py

No need to review this yet - more changes may be coming

Updated docstrings and PEP8 fixes for remainder of node

---

vantage6-server/vantage6/server/controller/query.py
vantage6-server/vantage6/server/model/base.py
vantage6-server/vantage6/server/model/collaboration.py
vantage6-server/vantage6/server/model/node.py
vantage6-server/vantage6/server/model/organization.py
vantage6-server/vantage6/server/model/result.py
vantage6-server/vantage6/server/model/role.py
vantage6-server/vantage6/server/model/rule.py
vantage6-server/vantage6/server/model/task.py
vantage6-server/vantage6/server/model/user.py
vantage6-server/vantage6/server/permission.py
vantage6-server/vantage6/server/resource/collaboration.py
vantage6-server/vantage6/server/resource/node.py
vantage6-server/vantage6/server/resource/organization.py
vantage6-server/vantage6/server/resource/port.py
vantage6-server/vantage6/server/resource/result.py
vantage6-server/vantage6/server/resource/role.py
vantage6-server/vantage6/server/resource/rule.py
vantage6-server/vantage6/server/resource/task.py
vantage6-server/vantage6/server/resource/user.py

Fix blocked database connections

---

vantage6-server/vantage6/server/resource/port.py

Error that got introduced with all recent fixes related to #534

Fixed erroneous session commit in delete port endpoint

---

.github/workflows/release.yml
docs/release_notes.rst
docs/use/node.rst
services/vpn-client/entry.sh
vantage6-node/vantage6/node/docker/vpn_manager.py

Added firewall rules for talking to algorithms that run on the same node.
You need to add special rules for when you want machines in a private network to talk to some other machine on the private network but with an external IP address. Apparently this is called [hairpinning](https://blog.lordvan.com/blog/learned-something-new-today-hairpin-nat-with-iptables-on-linux/)
Closes #336

336 bug separate containers on same node cannot talk to eachother over n2n

---

vantage6-server/vantage6/server/resource/common/auth_helper.py
vantage6-server/vantage6/server/resource/recover.py
vantage6-server/vantage6/server/resource/token.py
vantage6-server/vantage6/server/templates/mail/blocked_account.html
vantage6-server/vantage6/server/templates/mail/blocked_account.txt

The functions to do this were moved in one branch merged into 3.8, and not moved in the branch where sending email was implemented. This presumably went wrong in automerge, and has been corrected here

Fix sending email when user is blocked

---

vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/docker/docker_manager.py
vantage6-node/vantage6/node/docker/ssh_tunnel.py
vantage6-node/vantage6/node/docker/task_manager.py
vantage6-node/vantage6/node/docker/vpn_manager.py
vantage6-node/vantage6/node/proxy_server.py
vantage6-node/vantage6/node/server_io.py
vantage6-node/vantage6/node/socket.py
vantage6-node/vantage6/node/util/__init__.py

- Updated docstrings of node to python 3.10
- added a few missing ones
- Cleaned up some imports

Updated node docstrings

---

vantage6-server/tests_server/test_resources.py
vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/_version.py
vantage6-server/vantage6/server/cli/server.py
vantage6-server/vantage6/server/context.py
vantage6-server/vantage6/server/controller/fixture.py
vantage6-server/vantage6/server/db.py
vantage6-server/vantage6/server/default_roles.py
vantage6-server/vantage6/server/exceptions.py
vantage6-server/vantage6/server/mail_service.py
vantage6-server/vantage6/server/model/base.py
vantage6-server/vantage6/server/model/collaboration.py
vantage6-server/vantage6/server/model/role.py
vantage6-server/vantage6/server/model/rule.py
vantage6-server/vantage6/server/model/task.py
vantage6-server/vantage6/server/model/user.py
vantage6-server/vantage6/server/permission.py
vantage6-server/vantage6/server/resource/__init__.py
vantage6-server/vantage6/server/resource/common/auth_helper.py
vantage6-server/vantage6/server/resource/pagination.py
vantage6-server/vantage6/server/resource/token.py
vantage6-server/vantage6/server/resource/vpn.py
vantage6-server/vantage6/server/websockets.py

With this, all server functions should now have docstrings, with the exception of the Schema code, which will soon be refactored.
Also, I removed all the Union|Dict|List etc since we're now on 3.10

Updated server docstrings

---

vantage6-client/vantage6/client/algorithm_client.py

This is a reason the algorithmclient is probably not working yet

Added subclients to the algorithmclient

---

vantage6-server/server.sh

* default behaviour is preserved

Settable config file location for the server

---

vantage6-common/vantage6/common/docker/addons.py

Since the dates were not identical between local and remote, extracting the sha256 digest and determining if they are the same based on that
Fix #507

Fix for checking whether to pull a newer node/server image

---

docs/user/pyclient.rst

Clarified what RPC stands for in Python client user docs

---

vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/docker/task_manager.py

Prevent that tasks are killed if socket connection is temporarily lost

---

vantage6-client/vantage6/client/algorithm_client.py

Harm asked for this in #683 - no reason not to do so

Add organization_id as attribute to the algorithm client 

---

vantage6-server/vantage6/server/resource/common/output_schema.py
vantage6-server/vantage6/server/resource/user.py

This PR adds a few additional details to the user endpoint so that the UI can be more efficient in determining permissions.

Feature/added UI permissions to user endpoint

---

.github/workflows/release.yml
Makefile
SECURITY.md
docker-compose.yml
docs/algorithms/classic_tutorial.rst
docs/devops/contribute.rst
docs/devops/release.rst
docs/function-docs/server.rst
docs/node/node_config.yaml
docs/server/yaml/server_config.yaml
docs/user/api.rst
docs/user/pyclient.rst
docs/user/rclient.rst
docs/user/ui.rst
vantage6-common/vantage6/common/globals.py

mostly renaming in the docs to refer to latest major

Introduce new main version Cotopaxi

---

vantage6-server/vantage6/server/controller/fixture.py
vantage6/vantage6/cli/dev.py

`vdev` bugfixes

---

vantage6-common/vantage6/common/client/client_base.py
vantage6-server/vantage6/server/resource/common/input_schema.py

Allow creating task without databases

---

.github/workflows/release.yml
docs/node/use.rst
vantage6-client/vantage6/client/__init__.py
vantage6-common/vantage6/common/client/client_base.py
vantage6-common/vantage6/common/globals.py
vantage6/vantage6/cli/node.py

Use same minor version as server when starting the node

---

docs/function-docs/algorithm-tools.rst

Fix missing function docs for algorithm tools

---

vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py

- Handle pd.Dataframe properly
- correct 'type' to 'db_type'
Fix #872

Fixed broken data loading in mockClient

---

vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py

Flask proxy server handles any other value as true including 'False'

Specify algorithmClient boolean request parameters only if they are true

---

docs/release_notes.rst

Change/release notes 4.1

---

vantage6-algorithm-tools/requirements.txt
vantage6-algorithm-tools/setup.py

This dependency is required for reading Excel databases

Added OpenPyxl dependency to algorithm tools.

---

vantage6-algorithm-tools/requirements.txt
vantage6-algorithm-tools/setup.py
vantage6-server/vantage6/server/resource/common/input_schema.py
vantage6-server/vantage6/server/resource/ui/column.py

The worksheet_name variable was changed to sheet_name which is also used in the /task endpoint. Also, improved the docstring"

Fixed retrieving column names for Excel databases

---

vantage6-server/vantage6/server/resource/collaboration.py
vantage6-server/vantage6/server/resource/common/pagination.py
vantage6-server/vantage6/server/resource/node.py
vantage6-server/vantage6/server/resource/organization.py
vantage6-server/vantage6/server/resource/role.py
vantage6-server/vantage6/server/resource/rule.py
vantage6-server/vantage6/server/resource/run.py
vantage6-server/vantage6/server/resource/task.py
vantage6-server/vantage6/server/resource/user.py

Also improved the errors reported to the user

Fix sorting to explicitly use the resource table that is being requested

---

docs/user/pyclient.rst

Corrected calls to create tasks in Python client documentation

---

docs/server/yaml/server_config.yaml
vantage6-server/vantage6/server/resource/common/input_schema.py
vantage6-server/vantage6/server/resource/recover.py

Also:
- included return status in request to reset 2FA
- included 2FA in example server config file
- added docstring

Fix validation of request to recover 2FA secret

---

vantage6/vantage6/cli/node/start.py

Absolute path is no longer needed. Also Black formatted everything

updated help message for v6 node start

---

docs/node/node_config.yaml

Updated docstring

---

vantage6-common/vantage6/common/context.py
vantage6-common/vantage6/common/docker/addons.py
vantage6-common/vantage6/common/docker/network_manager.py
vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/docker/docker_manager.py
vantage6-node/vantage6/node/docker/vpn_manager.py
vantage6/tests_cli/test_node_cli.py
vantage6/vantage6/cli/context.py
vantage6/vantage6/cli/node/stop.py

- fix bug with VPN cleanup when iptables is not available but iptables-legacy is
- Cleanup volumes
Fix #1058

Fix node cleanup

---

vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/default_roles.py
vantage6-server/vantage6/server/model/role.py
vantage6-server/vantage6/server/permission.py

Add extra database column in Role to indicate if default role or not

---

docs/function-docs/cli.rst
docs/server/use.rst
vantage6/vantage6/cli/cli.py

Fix #1000 
@frankcorneliusmartin the most significant change here is `context_settings={"show_default": True}` I added in cli.py, which prints the defaults of all flags in CLI commands to the terminal.

Documentation of `v6 test` commands

---

vantage6-ui/src/app/components/forms/algorithm-store-form/algorithm-store-form.component.html
vantage6-ui/src/app/components/forms/algorithm-store-form/algorithm-store-form.component.ts
vantage6-ui/src/app/models/api/algorithmStore.model.ts
vantage6-ui/src/app/pages/collaboration/add-algo-store/add-algo-store.component.ts
vantage6-ui/src/app/pages/task/create/task-create.component.html
vantage6-ui/src/app/pages/task/create/task-create.component.scss
vantage6-ui/src/app/pages/task/create/task-create.component.ts

- No longer require user to fill in server URL when coupling an algorithm store (retrieving it from UI environment)
- when creating algorithms, show which algorithm store an algorithm is from

Improve integration algorithm store in UI

---

docs/node/node_config.yaml
vantage6-node/vantage6/node/__init__.py
vantage6/vantage6/cli/configuration_manager.py
vantage6/vantage6/cli/node/start.py

This addresses https://github.com/vantage6/vantage6/issues/1094
I'm PR'in to main, but feel free to change that.

Add node_extra_hosts option in node config

---

vantage6/requirements.txt
vantage6/setup.py
vantage6/vantage6/cli/algorithm/create.py
vantage6/vantage6/cli/algorithm/update.py

- Updated copier dependency
- New behaviour in 'v6 algorithm update' to skip questions previously answered
- New flag in 'v6 algorithm update' to allow user to change questions previously answered
- Using copier '--unsafe' flag in 'v6 algorithm create' and 'update' to be able to use new Python cleanup script defined in template creator

Minor updates to algorithm template generation

---

vantage6/requirements.txt
vantage6/setup.py

Update copier to fix pyyaml-include error with CLI

---

vantage6-algorithm-store/vantage6/algorithm/store/model/common/enums.py
vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py
vantage6-ui/src/app/helpers/regex.helper.ts
vantage6-ui/src/app/models/api/algorithm.model.ts
vantage6-ui/src/app/pages/task/create/task-create.component.html
vantage6-ui/src/app/pages/task/create/task-create.component.scss
vantage6-ui/src/app/pages/task/create/task-create.component.ts
vantage6-ui/src/app/pages/task/task.helper.ts

Feature/support list arguments in UI

---

vantage6-ui/src/app/components/forms/user-form/user-form.component.ts
vantage6-ui/src/app/helpers/api.helper.ts
vantage6-ui/src/app/pages/role/create/role-create.component.ts
vantage6-ui/src/app/pages/role/read/role-read.component.ts
vantage6-ui/src/app/pages/task/list/task-list.component.ts
vantage6-ui/src/app/pages/task/read/task-read.component.ts
vantage6-ui/src/app/pages/user/read/user-read.component.ts
vantage6-ui/src/app/services/role.service.ts
vantage6-ui/src/app/services/rule.service.ts
vantage6-ui/src/app/services/task.service.ts

E.g. when showing all organizations in a dropdown, it's important that not just the first page is shown
Fix #1126

Fix pagination in UI where necessary

---

vantage6-node/vantage6/node/docker/task_manager.py
vantage6-ui/src/app/pages/collaboration/create/collaboration-create.component.ts
vantage6-ui/src/app/pages/collaboration/read/collaboration-read.component.html
vantage6-ui/src/app/pages/collaboration/read/collaboration-read.component.ts
vantage6-ui/src/app/services/node.service.ts
vantage6-ui/src/assets/localizations/en.json

Feature/register missing nodes in UI

---

vantage6-ui/src/app/pages/role/read/role-read.component.html
vantage6-ui/src/app/pages/role/read/role-read.component.ts
vantage6-ui/src/app/services/role.service.ts
vantage6-ui/src/assets/localizations/en.json

Add option to delete roles in the UI

---

requirements.txt
vantage6-common/requirements.txt
vantage6-common/setup.py

Addresses https://github.com/vantage6/vantage6/issues/1232

Update to PyYAML 6.0.1 to fix broken build

---

vantage6-algorithm-tools/vantage6/algorithm/tools/wrap.py
vantage6-common/vantage6/common/client/deserialization.py

Maybe a (partial) fix for #1085

Improved error message for invalid JSON in input decoding

---

docs/algorithms/concepts.rst
docs/server/optional.rst

Fix dead link and improve docs for using private docker registry

---

vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
vantage6-client/vantage6/client/subclients/algorithm.py

And added `ui_visualizations` docstring to a few docstrings where it was missing
Fix #1089

Added client.algorithm.update() function

---

vantage6-ui/src/app/layouts/layout-default/layout-default.component.html
vantage6-ui/src/app/layouts/layout-default/layout-default.component.scss
vantage6-ui/src/assets/localizations/en.json

Sorry that my editor did some code formatting.

Styled collaboration and store selection banner

---

docs/algorithms/develop.rst
docs/features/node/linked_docker_service.rst
vantage6/vantage6/cli/context/algorithm_store.py
vantage6/vantage6/cli/context/server.py

- fix code formatting issue
- fix wrong example of environment variables in algorithm development section

Small docs fixes

---

vantage6-server/vantage6/server/default_roles.py
vantage6-ui/src/app/components/forms/collaboration-form/collaboration-form.component.ts

- remove permission for collaboration admin to create new collaboration
- fix in UI for what people are allowed to view on page to create collaborations

collaboration admin permission fixes

---

docs/algorithms/develop.rst

Fix outdated documentation for algorithm development

---

vantage6-client/vantage6/client/__init__.py
vantage6-server/vantage6/server/resource/organization.py
vantage6-ui/src/app/components/forms/role-form/role-form.component.ts
vantage6-ui/src/app/components/forms/user-form/user-form.component.ts
vantage6-ui/src/app/models/api/organization.model.ts
vantage6-ui/src/app/pages/admin/organization/read/organization-read.component.html
vantage6-ui/src/app/pages/admin/organization/read/organization-read.component.ts
vantage6-ui/src/app/pages/admin/role/create/role-create.component.ts
vantage6-ui/src/app/services/organization.service.ts
vantage6-ui/src/app/services/permission.service.ts
vantage6-ui/src/assets/localizations/en.json

Also added option to filter by multiple IDs on GET /organization endpoint, which is convenient in the UI. And fixed which organizations are visible in UI when creating roles/users
Fix #1120, #241

Implemented functionality to delete organizations (API, client and UI)

---

vantage6/vantage6/cli/dev/create.py
vantage6/vantage6/cli/dev/remove.py
vantage6/vantage6/cli/dev/start.py
vantage6/vantage6/cli/dev/stop.py

`v6 dev` Servers are now by default in the user directories 

---

docs/devops/contribute.rst

This is a dead link as we no longer use Github Discussions

Removed Github Discussions link

---

vantage6-server/vantage6/server/resource/collaboration.py

Added logic to delete studies when collaboration is removed

---

vantage6-ui/src/app/components/forms/user-form/user-form.component.html
vantage6-ui/src/app/components/forms/user-form/user-form.component.ts
vantage6-ui/src/app/layouts/layout-default/layout-default.component.html
vantage6-ui/src/app/layouts/layout-default/layout-default.component.ts
vantage6-ui/src/app/models/api/user.model.ts
vantage6-ui/src/app/pages/admin/user/read/user-read.component.html
vantage6-ui/src/app/pages/admin/user/read/user-read.component.ts
vantage6-ui/src/assets/localizations/en.json
vantage6-ui/src/environments/environment.development.ts

- added option to view own user details in the top right menu
- hide permissions/roles on user edit page if you are editing your own user, as you can't change them
- improved showing the buttons to edit own user on view user page

Improvements to editing your own user in the UI

---

vantage6-client/vantage6/client/__init__.py

username or password = None gave problems.

Adjusted the dict send from the recovery client

---

vantage6/vantage6/cli/dev/create.py

Add option to set UI image in v6 dev network

---

vantage6-ui/src/app/app.module.ts
vantage6-ui/src/app/components/table/table.component.html
vantage6-ui/src/app/pages/analyze/task/list/task-list.component.ts
vantage6-ui/src/app/pages/analyze/task/read/task-read.component.html
vantage6-ui/src/app/pages/analyze/task/read/task-read.component.ts
vantage6-ui/src/app/pipes/highlighted-text.pipe.ts

Fixed #1361 task list table bugs:
- Search input not working properly.
- When search input is active subtasks are shown, they're not filtered out again after emptying the input field.
- Pagination to first page not working properly.
Also fixed: 
- #1489  => Added study name to task read page and task list.

#1361 fixed task table filter and added study to list and read

---

CODE_OF_CONDUCT.md
README.md
docs/devops/index.rst

Community leaders == Community Admins in our case?

Added base code of conduct

---

vantage6-algorithm-tools/vantage6/algorithm/tools/mock_client.py
vantage6-client/vantage6/client/__init__.py
vantage6-common/vantage6/common/globals.py
vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/model/node.py
vantage6-server/vantage6/server/resource/event.py
vantage6-server/vantage6/server/resource/node.py
vantage6-server/vantage6/server/websockets.py

Added enum for the `AuthStatus` and set the node by default on offline

---

docs/release_notes.rst

Needs to be extended when the final code changes come in.

Change/add release notes 4.8

---

vantage6-common/vantage6/common/__init__.py
vantage6-node/vantage6/node/cli/node.py
vantage6/tests_cli/test_node_cli.py
vantage6/tests_cli/test_server_cli.py
vantage6/vantage6/cli/algostore/new.py
vantage6/vantage6/cli/node/new.py
vantage6/vantage6/cli/node/set_api_key.py
vantage6/vantage6/cli/server/new.py

cli: create config directory if it doesn't exist

---

docs/node/node_config.yaml

Add info on how to reset API key in example node configuration file

---

vantage6-ui/src/app/models/api/algorithm.model.ts
vantage6-ui/src/app/pages/analyze/task/create/task-create.component.html
vantage6-ui/src/app/pages/analyze/task/create/task-create.component.scss
vantage6-ui/src/app/pages/analyze/task/create/task-create.component.ts
vantage6-ui/src/app/pages/analyze/task/task.helper.ts
vantage6-ui/src/app/pages/analyze/template-task/create/template-task-create.component.html
vantage6-ui/src/app/pages/analyze/template-task/create/template-task-create.component.ts
vantage6-ui/src/app/pipes/highlighted-text.pipe.ts
vantage6-ui/src/assets/localizations/en.json

#1338 Combine algorithm and function selection for creating tasks

---

vantage6-ui/src/app/components/algorithm/display-algorithm/display-algorithm.component.html
vantage6-ui/src/app/pages/analyze/choose-collaboration/upload-private-key/upload-private-key.component.html
vantage6-ui/src/assets/localizations/en.json

Also clarified message when uploading private key that uploading a wrong key will allow you to view task metadata but not input and results.

Show algorithm digest on UI pages detailing an algorithm

---

vantage6-algorithm-store/vantage6/algorithm/store/__init__.py
vantage6-algorithm-store/vantage6/algorithm/store/model/function.py
vantage6-algorithm-store/vantage6/algorithm/store/resource/algorithm.py
vantage6-algorithm-store/vantage6/algorithm/store/resource/schema/input_schema.py
vantage6-client/vantage6/client/subclients/store/algorithm.py
vantage6-ui/src/app/app.module.ts
vantage6-ui/src/app/components/algorithm/display-algorithm/display-algorithm.component.html
vantage6-ui/src/app/components/forms/algorithm-form/algorithm-form.component.html
vantage6-ui/src/app/components/forms/algorithm-form/algorithm-form.component.ts
vantage6-ui/src/app/models/api/algorithm.model.ts
vantage6-ui/src/app/pages/analyze/task/create/task-create.component.ts
vantage6-ui/src/app/pages/store/algorithm/edit/algorithm-edit.component.ts
vantage6-ui/src/assets/localizations/en.json
vantage6-ui/src/styles.scss

Hide function in create task UI to prevent them from running it directly

#1093 - Hide function flag

---

vantage6-ui/src/app/app-routing.module.ts
vantage6-ui/src/assets/localizations/en.json

Bugfix/#1537 fix wrong breadcrumb UI

---

vantage6/vantage6/cli/test/feature_tester.py

Added MFA support to CLI command 'v6 test feature-test'

---

docs/index.rst
docs/introduction/quickstart.rst

This should help users to run v6 dev network easily

Add quickstart section to the docs 

---

docker/node-and-server.Dockerfile
vantage6-node/vantage6/node/docker/docker_manager.py
vantage6/tests_cli/test_node_cli.py
vantage6/vantage6/cli/node/start.py

Exit a node at startup time if a file-based database doesn't exist

---

charts/store/templates/server/store-configmap.yml

- Simple fix to couple the algo store and server

fix: update store configmap API endpoint path to /server

---

.github/workflows/release.yml
Makefile

Only add latest tag to infra images for final releases, not pre-releases

---

charts/node/templates/node-deployment.yml
devspace.yaml

Sorry @hcadavid I disabled these for now.

Temporary disabled the settable host alias and bind address

---

charts/server/templates/server/server-backend-configmap.yml
charts/server/values.yaml
vantage6-algorithm-store/tests_store/resources/test_v6server.py
vantage6-algorithm-tools/vantage6/algorithm/client/__init__.py
vantage6-algorithm-tools/vantage6/algorithm/tools/__init__.py
vantage6-backend-common/vantage6/backend/common/__init__.py
vantage6-client/vantage6/client/__init__.py
vantage6-common/vantage6/common/encryption.py
vantage6/vantage6/cli/__init__.py

- Add configurable server description and IP
- Introduce optional external database and RabbitMQ URI configurations
- Improve logging configuration with more granular settings
- Add support for dynamic or static JWT secret generation
- Update server backend configmap to handle new configuration options

feat: Enhance server configuration with more flexible options

---

vantage6-server/vantage6/server/__init__.py
vantage6-server/vantage6/server/resource/token.py

Not entirely sure about this, I guess need to check some more what this parameter is about

Using API path in setting auth path for JWT

---

vantage6-node/vantage6/node/__init__.py
vantage6-node/vantage6/node/docker/docker_manager.py
vantage6-node/vantage6/node/docker/task_manager.py
vantage6-server/vantage6/server/websockets.py
vantage6-ui/src/app/models/socket-messages.model.ts
vantage6-ui/src/app/pages/analyze/task/read/task-read.component.html
vantage6-ui/src/app/pages/analyze/task/read/task-read.component.ts
vantage6-ui/src/app/services/socketio-connect.service.ts

This PR implements a logging mechanism using Docker native `logs(stream=True)` for a running container. This should allow to easily see what is happening when an algorithm is running. 
Logs in the UI seem to be available also for killed tasks.

Feature/#1351 Live logging

---

vantage6-client/vantage6/client/subclients/dataframe.py

This addresses an issue similar to #1883: the 'session preprocessing' client implementation wasn't up-to-date with respecto to the changes made to its corresponding API/request schema.

Fixing session pre-processing client method

---

charts/store/templates/server/store-configmap.yml
charts/store/values.yaml
devspace.yaml

Ensure dev env runs for different k8s

---

charts/store/values.yaml
devspace.yaml

Expose databases for db GUI

---

dev/connect-store.py
dev/load-basic-fixtures.py
dev/purge_data.sh
dev/v6-session-basic-algorithm-store.json

* Also created some sessions while I was there
* Removed the `exit` as you want to continue deleting the others if one is missing

Added new functions to the local dev store

---

dev/purge_data.sh

Similar to what we changed when creating the directories is now also required for deleting them :-)

Ensure purging data works in WSL

---

docs/glossary.rst
docs/introduction/introduction.rst
docs/technical_reference/algorithms/sessions.rst

I set out to work on this due to #1469, but I was actually already quite happy with the sessions documentation. I have created #2030 to update the algorithm section of the docs but otherwise we can close #1469 and consider sessions docs completed as far as I'm concerned

Updated session documentation

---

docs/devops/develop_env.rst
docs/devops/index.rst

Fix #1837. Also addresses some comments made in #1686

Initial documentation devspace environment

---

docs/devops/develop_env.rst

Update devspace docs
